### ISSUE TITLE
Bluetooth sound not working

### ISSUE THREAD

**Issue by pencilcheck** [OpenEmu/DeSmuME-Core#3]
https://github.com/OpenEmu/OpenEmu/issues/2979

**Comment by clobber** [comment]
There isn't a reason why audio would work in one core plugin and not another, because they all use the same API, so something else must be wrong on your end.

**Comment by pencilcheck** [comment]
I don't understand what you mean by on my end. Can you elaborate a bit more?
If I need to reinstall cores, how do I do that?
